api:
  tokens:
    length:
      refresh_token: 100
      auth_token: 30
    expire:
      refresh_token: 20000 # 8640000 # 100d
      auth_token: 10000 # 86400 # 1d
socket: 
  port: 2345
postgres:
  host: "127.0.0.1"
  port: 5432
  user: "taha"
  pass: "1234"
  db: "chatapp_db"
redis:
  host: "127.0.0.1"
  port: 6379
  user:
  pass: