version: "3.0"
services:
    frontend:
        image: "node:14"
        container_name: "tahagram_frontend"
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
    backend:
        image: "node:14"
        container_name: "tahagram_backend"
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
            - "2345:2345"
    mongo:
        image: "mongo"
        container_name: "tahagram_database"
        volumes:
            - chatapp_database_volume:/data/db
        ports:
            - 27017:27017
    redis:
        image: "redis:latest"
        container_name: "tahagram_redis"
        ports:
            - "6379:6379"
volumes:
    chatapp_database_volume:
