version: "3.3"
services:
    backend:
        image: "node:14"
        container_name: "chat_app_backend"
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
            - "2345:2345"
        restart: always
        network_mode: "host"
    frontend:
        image: "node:14"
        container_name: "chat_app_frontend"
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        network_mode: "host"
    nginx:
        container_name: "chat_app_nginx"
        build:
            context: ./backend
            dockerfile: nginx.Dockerfile
        ports:
            - "5000:5000"
        network_mode: "host"
    mongo:
        image: "mongo"
        container_name: "chat_app_database"
        volumes:
            - chatapp_database_volume:/data/db
        ports:
            - 27017:27017
        network_mode: "host"
    redis:
        image: "redis:latest"
        container_name: "chat_app_redis"
        ports:
            - "6379:6379"
        network_mode: "host"

volumes:
    chatapp_database_volume:
